quarrel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quarrelapp.urls'), name='quarrelapp_urls'),
    path('/', include('websitemanage.urls'),
         name='websitemanage_urls'),
    path('accounts/', include('allauth.urls')),
]  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quarrelapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import string
import random
from django.utils.text import slugify

User = settings.AUTH_USER_MODEL


def rand_slug():
    return "".join(
        random.choice(string.ascii_letters + string.digits) for _ in range(6)
    )


class CommentPost(models.Model):
    """
    Content and likes model
    """
    content = models.TextField()
    likes = models.ManyToManyField(User, related_name="likes", blank=True)

    def number_of_likes(self):
        return self.likes.count()


class Post(models.Model):
    """
    Post model
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    content_one = models.OneToOneField(
        CommentPost, on_delete=models.CASCADE, related_name="content_post_one"
    )
    content_two = models.OneToOneField(
        CommentPost, on_delete=models.CASCADE, related_name="content_post_two"
    )
    description = models.TextField(default="")

    CLEANING = "CLEANING"
    JEALOUSY = "JEALOUSY"
    YOUNEVER = "YOUNEVER"
    OTHER = "OTHER"

    TITLE_CHOICES = [
        (CLEANING, "Cleaning"),
        (JEALOUSY, "Jealousy"),
        (YOUNEVER, "You never"),
        (OTHER, "Other"),
    ]
    title = models.CharField(
        max_length=13,
        choices=TITLE_CHOICES,
        default=CLEANING,
    )
    slug = models.SlugField(max_length=255, unique=True)
    date_published = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(
        User, related_name="content_likes", blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + "-" + self.title)
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ["-date_published"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    """
    Comment model
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=80)
    body = models.TextField(max_length=120)
    date_published = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["date_published"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

quarrelapp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import Comment, Post
from crispy_forms.layout import (Field, Layout, Row, Column, Submit)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description')

    content_one = forms.CharField(max_length=500)
    content_two = forms.CharField(max_length=500)


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea, label='')

    class Meta:
        model = Comment
        fields = ('body',)

templates/about.html
{% extends "base.html" %} {% load static %} {% block content %}

<!-- Header -->
<container>
  <div class="row d-flex justify-content-center text-center">
    <div class="col-md-6">
      <h1 class="display-3 gradient-text mt-3">About</h1>
      <p class="text-secondary">A brief history</p>
      <hr />
    </div>
  </div>
  <!-- Content story -->
  <div class="row d-flex justify-content-center text-center border shadow">
    <div class="col-md-6">
      <h2><span class="gradient-text">Once,</span></h2>
      <p>
        Not many weeks ago I stumbled upon an issue, not involving tissues, but
        a missus.
      </p>
      <p>
        A fair and beauty of a new appartment, a bright and shiny dishwasher,
      </p>
      <p>
        no longer the need for manual wash. Girlfriend, as I, marvelled at the
        machine and on that day
      </p>
      <p>
        We decided that no longer would one(<em>me, I whispered to myself</em>)
        ever solely do the dishes
      </p>
      <p>
        Together, armed with technology of dish-wonder, we raised our fists into
        the yonder
      </p>
      <p>
        No longer shall we, we said, fight about who's to blame for dirty
        dishes, for now a dishwasher will fulfill all of our wishes
      </p>
      <p>
        Fast forward a week, or so, the many of times the dishwasher had saved
        us in the past, it broke out in a crackle and left us manual washing to
        tackle.
      </p>
      <hr />
      <h3><span class="gradient-text">Then,</span></h3>
      <p>
        The dishes piled up, and no matter how many days I washed, she did none
        I learned.
      </p>
      <p>
        She said: "I've done them plenty of times, it's now your turn."<br />A
        lie I discern
      </p>
      <p>
        I responded with the sweetest of voice: "That's not true. I've done them
        all. How would you say that I wonder?"
      </p>
      <p>
        Her face red as blood, legs trembling in anger, and before the fight
        started I thought:
      </p>
      <p>
        Another pair of eyes on this Quarrel and our issues would be caught.
      </p>
    </div>
  </div>
  <!-- Contact us -->
  <div
    class="
      row
      flex-md-column
      justify-content-center
      text-center
      border
      shadow
      mt-3
    "
  >
    <div class="col-md-12 m-3">
      <h3 class="montserrat"><em>Please</em> don't contact us:</h3>
    </div>
    <div class="row">
      <div class="col-md-6">
        <p>
          Phone: <span class="text-muted"><br />+46703334455</span>
        </p>
      </div>
      <div class="col-md-6">
        <p>
          Email: <span class="text-muted"><br />justdont@quarrel.com</span>
        </p>
      </div>
    </div>
  </div>
</container>
{%endblock content%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Argument solver online" />
    <title>Relationship Quarrel</title>

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      rel="shortcut icon"
      href="{% static 'images/quarrel-favicon.jpg' %}"
      type="image/x-icon"
    />
    <!-- Font awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
      crossorigin="anonymous"
    ></script>

    <!-- Personal css -->

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  </head>

  <body class="d-flex flex-column h-100 bg-light">
    <header>
      <nav class="navbar navbar-color navbar-expand-lg fixed-top navbar-dark">
        <a class="navbar-brand display-3" href="{% url 'home' %}">QRL</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto pl-3">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about' %}"
                >About <span class="sr-only">(current)</span></a
              >
            </li>

            {% if user.is_authenticated %}
            <li>
              <a class="nav-link active" href="{% url 'user_post' %}"
                >Post &raquo;</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'account_signup' %}"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
          <!-- Gets activated if user is authenticated and on a large screen -->
          <div class="dropdown dropleft bigScreen">
            <a
              class="btn btn-custom montserrat text-white dropdown-toggle"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'profile' %}">My Posts</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'deactivate_user' %}"
                >Deactivate Account</a
              >
              <a class="dropdown-item" href="{% url 'delete_user' %}"
                >Delete Account</a
              >
              <a class="dropdown-item" href="{% url 'account_logout' %}"
                >Logout</a
              >
            </div>
          </div>
          <!-- Gets activated if user is authenticated and on a small screen -->
          <div class="dropdown smallScreen">
            <a
              class="btn btn-custom text-white dropdown-toggle"
              role="button"
              id="dropdownMenuLink"
              data-toggle="dropdown"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'profile' %}">My Posts</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'deactivate_user' %}"
                >Deactivate Account</a
              >
              <a class="dropdown-item" href="{% url 'delete_user' %}"
                >Delete Account</a
              >
              <a class="dropdown-item" href="{% url 'account_logout' %}"
                >Logout</a
              >
            </div>
          </div>
          {% else %}
          <form class="form-inline justify-content-centered">
            <a
              href="{% url 'account_login' %}"
              class="btn btn-custom btn-lg shadow text-white"
              role="button"
              aria-label="Post"
              >Login</a
            >
          </form>
          {% endif %}
        </div>
      </nav>
    </header>

    <!-- Messages -->
    <div class="container">
      <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2 text-center">
          {% for message in messages %}
          <div
            class="alert {{ message.tags }} alert alert-warning alert-dismissible fade show"
            id="msg"
            role="alert"
          >
            {{ message | safe }}
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        </div>
      </div>

      <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
      </main>

      <!-- Footer -->
    </div>
    <footer
      class="
        footer
        mt-5
        fixed-bottom
        position-relative
        footer-custom
        text-center text-white
      "
    >
      <div class="p-2">
        <div class="mb-1">
          <a
            class="btn btn-light btn-floating shadow m-1"
            href="https://www.facebook.com/"
            role="button"
            target="_blank"
            aria-label="Facebook link"
            ><i class="fab fa-facebook-f"></i
          ></a>

          <a
            class="btn btn-light shadow btn-floating m-1"
            href="https://twitter.com/"
            role="button"
            target="_blank"
            aria-label="Facebook link"
            ><i class="fab fa-twitter"></i
          ></a>

          <a
            class="btn btn-light shadow btn-floating m-1"
            href="https://www.merriam-webster.com/dictionary/argument"
            role="button"
            target="_blank"
            aria-label="Facebook link"
            ><i class="fas fa-book-open"></i
          ></a>

          <a
            class="btn bg-light shadow btn-floating m-1"
            href="https://www.instagram.com/"
            role="button"
            target="_blank"
            aria-label="Facebook link"
            ><i class="fab fa-instagram"></i
          ></a>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/deactivate_user.html
{% extends 'base.html' %} {% load i18n %} {% block content %}

<container>
  <div class="row d-flex justify-content-center text-center">
    <div class="col-md-6">
      <h1 class="display-4">
        <strong
          >Deactivation-for-a-<em
            ><span class="gradient-text">Vacation!</span></em
          ></strong
        >
      </h1>
      <hr />
      <p>
        <em>We'll just consider this a "See you later"-type-of-situation</em>
      </p>
      <!-- Deactivation form - deactivates user when clicked -->
      <form action="{% url 'deactivate_user' %}" method="POST" class="padding">
        {% csrf_token %} {{ form.as_p}}
        <button
          class="btn btn-primary btn-custom text-white montserrat"
          type="submit"
          name="action"
        >
          {% trans "Confirm" %} &laquo
        </button>
      </form>
    </div>
  </div>
</container>
{% endblock %}

templates/delete_user.html
{% extends 'base.html' %} {% load i18n %} {% block content %}

<container>
  <div class="row d-flex justify-content-center text-center">
    <div class="col-md-6">
      <h1 class="display-4">
        <strong
          >Deletion...<br /><em
            ><span class="gradient-text">Completion?</span></em
          ></strong
        >
      </h1>
      <hr />
      <p>
        <em
          >This is like that scene in Lord of the Rings when Frodo goes all
          "Shoo, Sam, shoo!" and Sam actually leaves(?)</em
        >
      </p>
      <p>
        <em
          >But that Po-Tay-To lover sure came back in the end. Maybe
          <strong>you will, too.</strong></em
        >
      </p>
      <!-- Deletion form - deletes user when clicked -->
      <form action="{% url 'delete_user' %}" method="POST" class="padding">
        {% csrf_token %} {{ form.as_p}}
        <button
          class="btn btn-primary btn-custom montserrat text-white"
          type="submit"
          name="action"
        >
          {% trans "Confirm" %} &laquo
        </button>
      </form>
    </div>
  </div>
</container>
{% endblock %}

templates/edit_post.html
{% extends 'base.html' %} {% block content %}
<!-- Edit post template -->
<form method="POST" class="mt-3 mb-3" action data-np-checked="1">
  {% csrf_token %}
  <h1 class="display-4"><strong>Edit your post:</strong></h1>
  <p>Finally, let the Internet decide who's correct in your Quarrel</p>
  <div class="form-group">
    <label for="title"><em>Choose an appropriate category:</em></label>
    <select class="form-control" name="title" id="id_title">
      <option value="CLEANING">Cleaning</option>
      <option value="JEALOUSY">Jealousy</option>
      <option value="YOUNEVER">You never...</option>
      <option value="OTHER">Other</option>
    </select>
  </div>
  <div class="form-group">
    <label for="id_description">Description of the argument:</label>
    <!-- Prepopulates the area of description -->
    <textarea
      name="description"
      class="form-control"
      id="id_description"
      required
      maxlength="130"
      value=""
      rows="2"
      data-np-checked="1"
    >
{{ post.description }}</textarea
    >
  </div>
  <hr />
  <h2>Fighter number one</h2>
  <div class="form-group">
    <label for="id_content_one">Fighter number one, state your case: </label>
    <!-- Prepopulates the area of content one -->
    <textarea
      class="form-control"
      name="content_one"
      id="id_content_one"
      maxlength="500"
      rows="3"
      required
      data-np-checked="1"
    >
{{ post.content_one.content }}</textarea
    >
  </div>
  <hr />
  <h2>Fighter number two</h2>
  <div class="form-group">
    <label for="id_content_two">Fighter number two, state your case: </label>
    <!-- Prepopulates the area of content two -->
    <textarea
      class="form-control"
      name="content_two"
      id="id_content_two"
      maxlength="500"
      rows="3"
      required
      data-np-checked="1"
    >
{{ post.content_two.content }}</textarea
    >
  </div>
  <hr />
  <input
    type="submit"
    value="Post"
    class="btn btn-custom text-white"
    data-np-checked="1"
  />
</form>

{% endblock content %}

templates/index.html
{% extends "base.html" %} {% load static %} {% block content %}

<div class="jumbotron bg-light border shadow text-center mb-0 mt-2">
  <h1 class="display-3">
    <strong><span class="gradient-text">Issues</span> at home?</strong>
  </h1>
  <p class="lead">
    Since the dawn of the creation of the Internet, it has been, without a
    doubt<span class="gradient-text">*</span>, the best place to ask for solid
    advice
  </p>
  <hr class="my-4" />
  <p class="text-secondary">
    <em
      >Is someone not doing the dishes? Cleaning? An argument unsolved? Instead
      of practicing your communication skills...</em
    >
  </p>
  <p class="lead">
    <a
      class="btn btn-custom btn-lg mt-3 shadow text-white"
      href="{% url 'user_post' %}"
      role="button"
      aria-label="Post"
      >Ask The Internet &raquo;</a
    >
  </p>
  <p class="float-right">
    <span class="gradient-text text-muted">*</span><em>Some doubt</em>
  </p>
</div>
<div class="row mt-3 border-top-2 border-right-2 border-left-2 shadow mb-1">
  <div class="col-12 background-gradient text-center align-middle shadow">
    <h2 class="m-2">QUARRELS</h2>
  </div>
</div>
<!-- Post section -->
<div class="container mx-auto mt-4 d-flex justify-content-center text-center">
  <div class="row img-fluid">
    {% for post in post_list %}
    <div class="col-md-4 shadow mt-2 col-sm-12 justify-content-center border">
      <div class="card card-height">
        {% if post.title == "CLEANING" %}
        <!-- Adds correct image depending on title chosen -->
        <img
          src="{% static 'images/CLEANING.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "OTHER" %}
        <img
          src="{% static 'images/OTHER.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "JEALOUSY" %}
        <img
          src="{% static 'images/JEALOUSY.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "YOUNEVER" %}
        <img
          src="{% static 'images/YOUNEVER.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% else %}
        <img
          src="https://i.imgur.com/FYqU8mB.jpg"
          class="card-img-top"
          alt="..."
        />
        {% endif %}
        <div class="card-body">
          <a href="{% url 'post_detail' post.slug %}" class="text-decoration-none text-reset post-link">
            <h5 class="gradient-text card-title font-weight-bold">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">
              <!-- posts date post published -->
              {{ post.date_published}}
            </h6>
          </a>
          <hr />

          <p class="card-text mr-2 ml-2">{{ post.description }}</p>
        </div>
          <div class="row d-flex card-footer text-center align-bottom">
            <div class="col-sm">
              <span class="text-secondary"
                ><i class="fas fa-heart heart-custom-purple"></i
              ></span>
              <span class="text-secondary">
                <!-- Posts content one likes -->
                {{ post.content_one.number_of_likes }}
              </span>
            </div>
            <div class="col-sm">
              <span class="text-secondary"
                ><i class="fas fa-heart heart-custom-orange"></i
              ></span>
              <span class="text-secondary">
                <!-- Posts content two likes -->
                {{ post.content_two.number_of_likes }}
              </span>
            </div>
          </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Pagination -->
</div>
{% if is_paginated %}
<div class="row d-flex justify-content-center mt-1">
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a
          href="?page={{ page_obj.previous_page_number }}"
          class="page-link background-gradient"
          >&laquo; PREV
        </a>
      </li>
      {% endif %} {% if page_obj.has_next %}
      <li class="page-item">
        <a
          href="?page={{ page_obj.next_page_number }}"
          class="page-link background-gradient"
        >
          NEXT &raquo;</a
        >
      </li>

      {% endif %}
    </ul>
  </nav>
</div>
{% endif %} {%endblock content%}

templates/profile.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="row border-top-2 border-right-2 border-left-2 shadow-sm mb-1">
  <div class="col-12 background-gradient text-center align-middle">
    <h2>YOUR QUARRELS</h2>
  </div>
</div>
<div class="container mx-auto mt-4 d-flex justify-content-center text-center">
  <div class="row">
    <!-- Displays posts connected to logged in user -->
    {% for post in user_posts %}
    <div
      class="col-md-4 mt-2 col-sm-12 justify-content-center border title-custom"
    >
      <!-- Displays correct image depending on title -->
      <div class="card card-height">
        {% if post.title == "CLEANING" %}
        <img
          src="{% static 'images/CLEANING.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "OTHER" %}
        <img
          src="{% static 'images/OTHER.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "JEALOUSY" %}
        <img
          src="{% static 'images/JEALOUSY.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% elif post.title == "YOUNEVER" %}
        <img
          src="{% static 'images/YOUNEVER.jpg' %}"
          class="card-img-top"
          alt="..."
        />
        {% else %}
        <img
          src="https://i.imgur.com/FYqU8mB.jpg"
          class="card-img-top"
          alt="..."
        />
        {% endif %}
        <div class="card-body">
          <a href="{% url 'post_detail' post.slug %}" class="post-link">
            <h5 class="card-title link-dark">{{ post.title }}</h5>
          </a>
          <hr />

          <p class="card-text">{{ post.description }}</p>
          <div class="row d-flex text-center">
            <div class="col-sm">
              <span class="text-secondary"
                ><i class="fas fa-heart heart-custom-purple"></i
              ></span>
              <span class="text-secondary">
                {{ post.content_one.number_of_likes }}
              </span>
            </div>
            <div class="col-sm">
              <span class="text-secondary"
                ><i class="fas fa-heart heart-custom-orange"></i
              ></span>
              <span class="text-secondary">
                {{ post.content_two.number_of_likes }}
              </span>
            </div>
          </div>
          <hr />
          <!-- Securely displays edit/delete for user -->
          {% if request.user == post.user %}

          <button
            type="button"
            class="btn btn-custom text-white btn-sm text-center"
            data-toggle="modal"
            data-target="#exampleModal"
          >
            <i class="far fa-trash-alt"></i>
          </button>
          <a
            href="{% url 'edit_post' post.slug %}"
            role="button"
            class="btn btn-custom text-white btn-sm text-center"
            ><i class="far fa-edit"></i
          ></a>
          <!-- Modal for button -->
          <div
            class="modal fade"
            id="exampleModal"
            tabindex="-1"
            role="dialog"
            aria-hidden="true"
          >
            <div class="modal-dialog text-center" role="document">
              <div class="modal-content text-center">
                <div class="modal-header">
                  <h5 class="modal-title text-center">Delete Post</h5>
                  <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>
                    <em
                      >Are you sure you want to delete your post?<br />If so,
                      click the trash that can.</em
                    >
                  </p>
                </div>
                <div class="modal-footer text-center">
                  <a href="{% url 'delete' post.slug %}"
                    ><i class="far fa-trash-alt"></i
                  ></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %} {% empty %}
    <!-- Displays in case user has no posts,  -->
    <div class="text-center d-flex justify-content-center flex-column">
      <h1 class="display-4">
        You have no <span class="gradient-text">quarrels</span>.<br />
        What are you, a <span class="gradient-text">drama-free</span> person?
      </h1>
      <h3>
        <em
          >Get yourself out there, turn every stone, rattle some feathers, and
          find some!</em
        >
      </h3>
      <hr />
      <p class="lead">
        <a
          class="btn btn-custom btn-lg text-white mt-4"
          href="{% url 'user_post' %}"
          role="button"
          aria-label="Post"
          >Ask The Internet &raquo;</a
        >
      </p>
      <br />
      <hr />
      <p>
        <em>I believe in you.</em>
      </p>
      <i class="fas fa-heart heart-custom-purple"></i>
    </div>
    {% endfor %} {% endblock content %}
  </div>
</div>

templates/user_post.html
{% extends 'base.html' %} {% block content %}

<!-- User post section -->
<form method="POST" class="mt-3 mb-3" action data-np-checked="1">
  {% csrf_token %}
  <h1 class="display-4">
    <strong>Enter the <span class="gradient-text">Arena!</span></strong>
  </h1>
  <p>Finally, let the Internet decide who's correct in your Quarrel</p>
  <div class="form-group">
    <!-- Allows user to choose category -->
    <label for="title"><em>Choose an appropriate category:</em></label>
    <select class="form-control" name="title" id="id_title">
      <option value="CLEANING">Cleaning</option>
      <option value="JEALOUSY">Jealousy</option>
      <option value="YOUNEVER">You never...</option>
      <option value="OTHER">Other</option>
    </select>
  </div>
  <!-- Allows user to write a description -->
  <div class="form-group">
    <label for="id_description">Description of the argument:</label>
    <textarea
      name="description"
      class="form-control"
      id="id_description"
      maxlength="120"
      required
      rows="2"
      data-np-checked="1"
    ></textarea>
  </div>
  <hr />
  <h2>Fighter number one</h2>
  <!-- Allows user to write first argument -->
  <div class="form-group">
    <label for="id_content_one">Fighter number one, state your case: </label>
    <textarea
      class="form-control"
      name="content_one"
      id="id_content_one"
      maxlength="500"
      rows="2"
      required
      data-np-checked="1"
    ></textarea>
  </div>
  <hr />
  <h2>Fighter number two</h2>
  <!-- Allow user to write second argument -->
  <div class="form-group">
    <label for="id_content_two">Fighter number two, state your case: </label>
    <textarea
      class="form-control"
      name="content_two"
      id="id_content_two"
      maxlength="500"
      rows="2"
      required
      data-np-checked="1"
    ></textarea>
  </div>
  <hr />
  <input
    type="submit"
    value="Post"
    class="btn btn-md btn-custom text-white montserrat"
    data-np-checked="1"
  />
</form>

{% endblock content %}